[package]
name = "radish"
version = "0.1.0"
authors = ["Hyunsik Choi <hyunsik.choi@gmail.com>"]
description = "Radish is a set of core libraries"

[dependencies]
crossbeam = "0.2.10"
env_logger = "0.3.5"
log = "0.3.6"
rustc-serialize = "0.3.22"